spring.application.name=server
server.port=8080

# Spring Data MongoDB Atlas URI
spring.data.mongodb.uri=mongodb+srv://mahasanjit08_db_user:cKxmGy4BTj7ipzki@cluster0.im8ma4u.mongodb.net/project_h?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=mongodb+srv://mahasanjit08_db_user:cKxmGy4BTj7ipzki@cluster0.im8ma4u.mongodb.net/project_h?retryWrites=true&w=majority&appName=Cluster0
