spring.application.name=farmer-service
server.port=8081

# Spring Data JPA MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-a50759b-selvarajaswath62-cffc.g.aivencloud.com:14390/defaultdb?sslMode=REQUIRED&verifyServerCertificate=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

